# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RkuxXNB5SRQbm5CZYK0dTHjE6MOe0Mr
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# 1. Page window configurations
st.set_page_config(page_title="E-Commerce Recommender System", layout="wide")

st.title("🛍️ Advanced E-Commerce Recommendation Portal")
st.markdown("Query the recommendation engine using a User ID (KMeans Cluster items) or an Item ID (Cosine Similarity products).")
st.markdown("---")

# 2. Memory optimized caching loader designed for your exact dictionary bundle keys
@st.cache_resource
def load_recommendation_bundle():
    # Load the bundle generated at the end of your training notebook
    bundle = joblib.load("rakesh_deployment.pkl")
    return (
        bundle["raw_ratings_df"],
        bundle["cluster_map_df"],
        bundle["item_similarity_df"],
        bundle["product_cluster_mapping"]
    )

try:
    raw_df, cluster_df, item_similarity_df, product_cluster_mapping = load_recommendation_bundle()
    st.sidebar.success("✅ Operational matrices, ratings, and cluster maps loaded.")
except Exception as e:
    st.sidebar.error(f"❌ Initialization failure: {e}")
    st.stop()

# 3. User Interface Tabs
tab1, tab2 = st.tabs(["👤 Option 1: Recommend Products via User ID", "📦 Option 2: Recommend Products via Item ID"])

# =========================================================================
# OPTION 1: USER-ID TRACK (KMEANS CLUSTER)
# =========================================================================
with tab1:
    st.subheader("Cluster-Based Product Discovery (KMeans)")
    st.markdown("Enter a User ID to identify their cluster and find the top-rated items inside that specific cohort.")

    col1_u, col2_u = st.columns([1, 2])

    with col1_u:
        sample_users = list(cluster_df['userId'].head(5).values)
        st.info(f"Sample User IDs to try: `{', '.join(sample_users)}`")

        input_user_id = st.text_input("Enter User ID String:", value=sample_users[0]).strip()
        top_n_user = st.slider("Number of products to recommend (User):", min_value=3, max_value=15, value=5)
        submit_user = st.button("Generate Products for User", type="primary")

    with col2_u:
        if submit_user:
            if input_user_id in cluster_df['userId'].values:
                # Fetch target user's assigned cluster label
                user_meta = cluster_df[cluster_df['userId'] == input_user_id].iloc[0]
                assigned_cluster = int(user_meta['KMeans_Cluster'])

                st.metric(label="User Cohort Group", value=f"Cluster #{assigned_cluster}")
                st.success(f"User `{input_user_id}` belongs to **Cluster Group {assigned_cluster}**.")

                # Extract peer members and query group transactions
                peer_user_ids = cluster_df[cluster_df['KMeans_Cluster'] == assigned_cluster]['userId'].values
                cluster_ratings = raw_df[raw_df['userId'].isin(peer_user_ids)]

                # Compute explicit aggregate statistics per item inside this cluster
                product_stats = cluster_ratings.groupby('productId').agg(
                    Average_Rating=('rating', 'mean'),
                    Total_Ratings_Count=('rating', 'count')
                ).reset_index()

                recommended_products = product_stats.sort_values(
                    by=['Average_Rating', 'Total_Ratings_Count'],
                    ascending=[False, False]
                ).head(top_n_user)

                # Inject metadata tracking attributes
                recommended_products['Cluster_Type'] = f"Cluster {assigned_cluster}"
                recommended_products.columns = ["Product ID (SKU)", "Avg Rating (In Cluster)", "Total Ratings Count", "Cluster Type"]

                st.markdown(f"#### 🎯 Top {top_n_user} Items for Cluster #{assigned_cluster}")
                st.dataframe(recommended_products.style.background_gradient(cmap="viridis", subset=["Avg Rating (In Cluster)"]), use_container_width=True)
            else:
                st.error("Provided User ID does not exist inside system matrices.")

# =========================================================================
# OPTION 2: ITEM-ID TRACK (COSINE SIMILARITY)
# =========================================================================
with tab2:
    st.subheader("Cross-Sell Inventory Discovery (Cosine Similarity)")
    st.markdown("Enter an Item Product ID to find similar items based on vector proximity matrices, complete with ratings and cluster attributes.")

    col1_i, col2_i = st.columns([1, 2])

    with col1_i:
        sample_products = list(item_similarity_df.index[:5])
        st.info(f"Sample Product IDs to try: `{', '.join(sample_products)}`")

        input_item_id = st.text_input("Enter Product ID (SKU):", value=sample_products[0]).strip()
        top_n_item = st.slider("Number of products to recommend (Item):", min_value=3, max_value=15, value=5)
        submit_item = st.button("Generate Similar Products", type="primary")

    with col2_i:
        if submit_item:
            if input_item_id in item_similarity_df.index:
                # Fetch target item's cluster type
                target_cluster = product_cluster_mapping.get(input_item_id, "Unknown")
                st.success(f"Item `{input_item_id}` identified (Belongs to Cluster Type: {target_cluster}). Extracting closest matrix profiles...")

                # 1. Fetch cosine similarity neighbors (safely drop self)
                similar_items_series = item_similarity_df[input_item_id].drop(labels=[input_item_id], errors='ignore')
                top_similar_items = similar_items_series.sort_values(ascending=False).head(top_n_item)

                # 2. Build tracking reference dataframe
                sim_df = pd.DataFrame({
                    "productId": top_similar_items.index,
                    "Cosine Similarity Score": top_similar_items.values
                })

                # 3. Enrich output data with individual metrics and its cluster type mappings
                enriched_recommendations = []
                for _, row in sim_df.iterrows():
                    p_id = row['productId']
                    p_ratings = raw_df[raw_df['productId'] == p_id]

                    avg_r = p_ratings['rating'].mean() if not p_ratings.empty else 0.0
                    count_r = p_ratings['rating'].count() if not p_ratings.empty else 0

                    assigned_cluster_type = product_cluster_mapping.get(p_id, "Unknown")
                    if assigned_cluster_type != "Unknown":
                        assigned_cluster_type = f"Cluster {assigned_cluster_type}"

                    enriched_recommendations.append({
                        "Product ID (SKU)": p_id,
                        "Cosine Similarity Score": round(row['Cosine Similarity Score'], 4),
                        "Average Rating": round(avg_r, 2),
                        "Total Ratings Count": int(count_r),
                        "Cluster Type": assigned_cluster_type
                    })

                final_item_output = pd.DataFrame(enriched_recommendations)
                st.markdown(f"#### 🎯 Top {top_n_item} Similar Products for `{input_item_id}`")
                st.dataframe(final_item_output.style.background_gradient(cmap="magma", subset=["Cosine Similarity Score"]), use_container_width=True)
            else:
                st.error("Target SKU key mismatch. Value not found inside system matrix configurations.")